name: adv_bmi_calculator
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.0
  path_provider: ^2.1.5
  animations: ^2.0.11
  fl_chart: ^0.69.0
  url_launcher: ^6.3.1
  intl: ^0.17.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1  # Ensure you're using a compatible version
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/app_icon.png

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icons/app_icon.png"
